ezpublish:
    system:
        site_group:
            design: site_design

            content_view:
                full:
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Id\Location: 2

                    ride:
                        template: '@ezdesign/full/ride.html.twig'
                        controller: 'AppBundle:Ride:viewRideWithLandmarks'
                        match:
                            Identifier\ContentType: [ride]
                    ride_list:
                        template: '@ezdesign/full/ride_list.html.twig'
                        match:
                            Identifier\ContentType: [folder]

                    contact:
                        controller: 'app.controller.contactform:showContactFormAction'
                        template: '@ezdesign/full/contact.html.twig'
                        match:
                            Identifier\ContentType: [contact]

                line:
                    ride:
                        template: '@ezdesign/line/ride.html.twig'
                        match:
                            Identifier\ContentType: 'ride'

                    landmark:
                        template: '@ezdesign/line/landmark.html.twig'
                        match:
                            Identifier\ContentType: 'landmark'
                home:
                    ride_list:
                        template: '@ezdesign/list/rides.html.twig'
                        controller: 'AppBundle:Ride:getAllRides'
                        match:
                            Identifier\ContentType: [folder]


            user_registration:
                templates:
                    form: '@ezdesign/user/registration_form.html.twig'
                    confirmation: '@ezdesign/user/registration_confirmation.html.twig'
